### ISSUE TITLE
Running pspy64&32 on debian.

### ISSUE THREAD

**Issue by Ce0tOS** [DominicBreuker/pspy#3] opened 2019-03-30 18:37 UTC
Just in case anyone knows how to solve this error while running pspy : 
ERROR: reading inotify buffer: reading from inotify fd 3: errno: 22

tried to run a few minutes, also did not help.

**Comment by Bechma** [comment] 2019-04-06 07:44
I'm having the same problem

**Comment by DominicBreuker** [comment] 2019-04-09 19:09
could it be that a machine which is particularly not heavy could help me reproducing the issue you guys experience? ;)

**Comment by Bechma** [comment] 2019-04-09 19:33
For me it's a Kali Linux under VirtualBox, when I launch pspy64 or pspy64s after a couple of seconds the terminal gets full of "ERROR: reading inotify buffer: reading from inotify fd 3: errno: 22". I have to open a new terminal and kill the process(also the cpu usage increase a lot).

**Comment by DominicBreuker** [comment] 2019-04-09 20:03
ok for me it happened on the Lightweight HTB machine and I just assumed this must have been due to selinux restricting it somehow. will investigate a bit with a VM

**Comment by Mabu2** [comment] 2019-06-10 17:15
Same problem happening to me on CentOS 7.   Runs for a few minutes ok, then just starts spitting out over and over:

    ERROR: reading inotify buffer: reading from inotify fd 3: errno: 22

**Comment by mdurancarreras** [comment] 2019-07-23 12:53
I have the same problem in Kali Linux 2018, 2019 and Ubuntu 16.04 under VirtualBox. Any solution?

**Comment by juouy** [comment] 2019-08-08 16:42
Same problem. It just does not work. Might author elaborate why?

**Comment by DominicBreuker** [comment] 2019-08-11 21:04
I have a theory. The error occurs [here](https://github.com/DominicBreuker/pspy/blob/d2c836272937a3056bed4864c6fbdea5f47139e5/internal/fswatcher/inotify/inotify.go#L75) when we execute the `read` syscall. errno 22 is EINVAL meaning the argument is invalid. The argument is the buffer into which we read, which comes from [here](https://github.com/DominicBreuker/pspy/blob/d2c836272937a3056bed4864c6fbdea5f47139e5/internal/fswatcher/fswatcher.go#L115). inotify [docs](http://man7.org/linux/man-pages/man7/inotify.7.html) say it may happen if the buffer is too small and gives instructions how to size it. I think I've put a bad value. Will update code and then you guys tell me if the error goes away? (still can't reproduce this locally. for me the go syscall wrapper just seems to hang in these cases...).

**Comment by DominicBreuker** [comment] 2019-08-11 21:28
New release is out.

**Comment by mdurancarreras** [comment] 2019-08-11 21:43
I have the same problem... 

"ERROR: reading inotify buffer: reading from inotify fd 3: errno: 22" 

Thanks!

**Comment by DominicBreuker** [comment] 2019-08-12 12:52
did you use the newly released one?

**Comment by mdurancarreras** [comment] 2019-08-12 14:19
I think I found the solution ... All this time I used Terminator as a console, I still receive the same error if I run it from it, but if I run it from the terminal, everything works correctly.

**Comment by sayanthanpera** [comment] 2019-08-13 17:40
I have the same issue.. I downloaded pspy64 just now from "64 bit big, static version: pspy64 download".
Linux kali-host 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux
![Screenshot from 2019-08-13 23-08-48](https://user-images.githubusercontent.com/18692578/62963929-94ba1f00-be1f-11e9-8eb8-7bdd0b6dc314.png)

**Comment by DominicBreuker** [comment] 2019-08-22 18:43
this looks a lot like the previous version, not the new release. I further added a log message to program startup to print the version. current one is `v1.2.0`. It will also just kill itself now if the errno 22 error occurs and not print all these messages. 
I still hope they won't come anymore since the buffer should now accommodate even the longest linux file names. we will see...

**Comment by sayanthanpera** [comment] 2019-08-26 19:20
New release(v1.2.0). Work fine. Awesome.

**Comment by DominicBreuker** [comment] 2019-10-08 19:52
Cool :)
I will close this one. Please open a new issue if the error reappears.

**Closed** 2019-10-09 06:51 UTC
